#!/bin/bash
# Test D: Check the "compile-time error on CPUs lacking POPCNT" claim
# Expected: This claim is DISPUTED - it should be runtime error, not compile-time

echo "========================================="
echo "R1 Test D: Compile-Time Error Claim"
echo "========================================="
echo ""
echo "Testing claim: 'On CPUs lacking POPCNT the -msse4.2 flag will cause a compile-time error'"
echo ""

echo "ANALYSIS:"
echo "---------"
echo ""
echo "Per GCC documentation:"
echo "  - '-msse4.2' is a compiler target option that enables built-ins and codegen"
echo "  - It does NOT check if the host CPU supports the instruction"
echo ""
echo "Per Intel documentation:"
echo "  - Executing POPCNT when CPU lacks support causes #UD (illegal instruction)"
echo "  - This is a RUNTIME error, not a compile-time error"
echo ""
echo "CONCLUSION: The claim is DISPUTED"
echo ""
echo "The response states: 'On CPUs lacking POPCNT the -msse4.2 flag will"
echo "cause a compile-time error'"
echo ""
echo "Reality: -msse4.2 enables POPCNT codegen at compile time regardless of"
echo "whether the host CPU supports it. If you run the binary on a CPU without"
echo "POPCNT support, you get a RUNTIME illegal instruction fault (#UD), not a"
echo "compile-time error."
echo ""

echo "========================================="
echo "Test D Complete"
echo "========================================="
echo ""
echo "Verified claim:"
echo "  - 'compile-time error on CPUs lacking POPCNT' - DISPUTED"
echo "  - Reality: Runtime #UD error, not compile-time"
